app/base/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String, DateTime

from app import db, login_manager
import bcrypt

class Users(db.Model, UserMixin):

    __tablename__ = 'users'

    id = Column(Integer, primary_key=True, nullable=False, unique=True, autoincrement=True)
    username = Column(String(45), nullable=False, unique=True)
    email = Column(String(255), nullable=False, unique=True)
    salt = Column(String(255), nullable=False, unique=True)
    password = Column(String(255))
    first_name = Column(String(150))
    last_name = Column(String(150))
    date_created = Column(DateTime)
    date_updated = Column(DateTime)
    remember_token = Column(String(255), unique=True)
    sector = Column(String(45))
    watchlist = Column(String(45))
    
    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            setattr(self, property, value)

        self.password = bcrypt.hashpw(self.password.encode(), self.salt.encode()).decode() 

    def get_id(self):
        return self.remember_token
    
    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(remember_token=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, SelectField, BooleanField
from wtforms.validators import InputRequired, Email, DataRequired, Length

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])
    remember_me = BooleanField('Remember me', id='remember_me_login')

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired(), Length(max=45)])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email(), Length(max=255)])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired(), Length(max=255)])
    sector = SelectField('Sector', id='sector_create', choices=[(x, x) for x in ['Consumer Discretionary', 'Consumer Staples', 'Energy',
                                                                'Financial Services', 'Healthcare', 'Materials & Processing',
                                                                'Producer Durables', 'Technology', 'Utilities']])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import Users

import bcrypt
import uuid
import datetime

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form and login_form.validate():
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()
        
        # Check the password
        if user and bcrypt.checkpw(password.encode(), user.password.encode()):
            login_user(user, remember = ('remember_me' in request.form))
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'accounts/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'accounts/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form and create_account_form.validate():
        username  = request.form['username']
        email     = request.form['email'   ]

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Username already registered',
                                    success=False,
                                    form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template( 'accounts/register.html', 
                                    msg='Email already registered', 
                                    success=False,
                                    form=create_account_form)

        attrs = dict(request.form)
        attrs['salt'] = bcrypt.gensalt().decode()
        attrs['remember_token'] = str(uuid.uuid4())
        attrs['first_name'] = 'Planty'
        attrs['last_name'] = 'Investments'

        current_timestamp = datetime.datetime.utcnow()
        attrs['date_created'] = current_timestamp
        attrs['date_updated'] = current_timestamp
        attrs['watchlist'] = ''

        # else we can create the user
        user = Users(**attrs)
        db.session.add(user)
        db.session.commit()

        return render_template( 'accounts/register.html', 
                                msg='User created please <a href="/login">login</a>', 
                                success=True,
                                form=create_account_form)

    else:
        return render_template( 'accounts/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('page-403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('page-403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('page-404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('page-500.html'), 500

app/base/templates/includes/_formhelpers.html
{% macro render_errors(field) %}
  {% if field.errors %}
	{% for error in field.errors %}
		<div class="text-danger mt-3 ml-3">{{ error | safe }}</div>
	{% endfor %}
  {% endif %}
{% endmacro %}

app/base/templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-center">
		  <div class="row align-items-center justify-content-center">
			&copy; 2020
		  </div>
        </div>
      </div>
    </footer>

app/base/templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-center">
		  <div class="row align-items-center justify-content-center">
			&copy; 2020
		  </div>
        </div>
      </footer>

app/base/templates/includes/navigation-fullscreen.html
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="/static/assets/img/brand/white.png">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/blue.png">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <hr class="d-lg-none" />
      <ul class="navbar-nav align-items-lg-center ml-lg-auto">
		<!--
        <li class="nav-item">
          <a class="nav-link nav-link-icon" 
             href="https://github.com/vmalepati1/Stock-Screener-Dashboard" 
             target="_blank" data-toggle="tooltip" data-original-title="Open-source code on Github">
            <i class="fab fa-github"></i>
            <span class="nav-link-inner--text d-lg-none">Github</span>
          </a>
        </li>
		-->
		
		<li class="nav-item">
		  <a class="nav-link nav-link-icon" href={{ url_for('base_blueprint.login') }}>
			<span class="nav-link-inner--text">Login</span>
		  </a>
		</li>
		
		<li class="nav-item">
		  <a class="nav-link nav-link-icon" href={{ url_for('base_blueprint.register') }}>
			<span class="nav-link-inner--text">Register</span>
		  </a>
		</li>
      </ul>
    </div>
  </div>
</nav>

app/base/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input id="searchBar" class="form-control" placeholder="Filter" onkeyup="searchLimiter()" type="text">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right">
            <div class="row shortcuts px-4">
              <a href="https://www.google.com/calendar" target="_blank" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
				<!--
				<br />
                <small>Calendar</small>
				-->
              </a>
              <a href="https://www.google.com/gmail/" target="_blank" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
				<!--
				<br />
                <small>Email</small>
				-->
              </a>
              <a href="https://finance.yahoo.com/" target="_blank" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-chart-bar-32"></i>
                </span>
				<!--
				<br />
                <small>Yahoo Finance</small>
				-->
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  <div class="media align-items-center">
				<i class="ni ni-single-02 text-yellow"></i>
				<div class="media-body ml-2 d-none d-lg-block">
				  <span class="mb-0 text-sm  font-weight-bold">{{ current_user.username }}</span>
				</div>
			  </div>
			</a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a class="dropdown-item {% if 'profile' in segment %} active {% endif %}" 
               href="/profile">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{{ url_for('base_blueprint.logout') }}" class="dropdown-item">
              <i class="ni ni-user-run"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/base/templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

app/base/templates/includes/sidenav.html
<div class="modal fade" id="modal-default" tabindex="-1" role="dialog" aria-labelledby="modal-default" aria-hidden="true">
	 <div class="modal-dialog modal- modal-dialog-centered modal-" role="document">
		<div class="modal-content">
		   <div class="modal-header">
			  <h4 class="modal-title" id="modal-title-default">Product information</h4>
			  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
			  <span aria-hidden="true">×</span>
			  </button>
		   </div>
		   <div class="modal-body">
			  <p>
			  This is an administration dashboard meant to help you manage your portfolio within specific sectors.
			  It provides tools that enable you to actively manage your watchlist, view the top gainers within your sector,
			  view which equities are being purchased by hedge funds, view insider trading reports, analyze financial data, 
			  view DCF models of investments, and forecast price action using machine learning algorithms. Some of these
			  features require that you first add some equities to your watchlist using the "Add symbol" button, and then 
			  you will be able to use the allocations tab, which tells you the optimal weightings for your equities
			  using a Monte Carlo simulation and historical data. The other tabs have drop downs in order to help you 
			  pick certain stocks and sectors to better analyze them.
			  </p>
		   </div>
		</div>
	 </div>
  </div>


<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="/">
        <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img">
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
		  <li class="nav-item">
            <a class="nav-link {% if 'watchlist' in segment %} active {% endif %}" 
               href="/watchlist/1d">
              <i class="ni ni-glasses-2"></i>
              <span class="nav-link-text">Watchlist</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'allocations' in segment %} active {% endif %}" 
               href="/allocations">
              <i class="ni ni-chart-pie-35 text-orange"></i>
              <span class="nav-link-text">Allocations</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'gainers' in segment %} active {% endif %}" 
               href="/top_gainers/{{ current_user.sector }}/1d">
              <i class="fas fa-percent text-info"></i>
              <span class="nav-link-text">Top gainers</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'hedge' in segment %} active {% endif %}" 
               href="/hedge_funds/{{ current_user.sector }}">
              <i class="ni ni-building text-primary"></i>
              <span class="nav-link-text">Hedge funds</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'insider' in segment %} active {% endif %}" 
               href="/insider_trading/{{ current_user.sector }}">
              <i class="ni ni-badge text-green"></i>
              <span class="nav-link-text">Insider trading</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'financials' in segment %} active {% endif %}" 
               href="/financials/{{ current_user.sector }}">
              <i class="ni ni-archive-2 text-pink"></i>
              <span class="nav-link-text">Financials</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'dcf' in segment %} active {% endif %}" 
               href="/dcf">
              <i class="ni ni-money-coins text-yellow"></i>
              <span class="nav-link-text">DCF</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'forecasts' in segment %} active {% endif %}" 
               href="/forecasts">
              <i class="ni ni-calendar-grid-58"></i>
              <span class="nav-link-text">Forecasts</span>
            </a>
          </li>
		  
		  <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}" 
               href="/profile">
              <i class="ni ni-single-02 text-orange"></i>
              <span class="nav-link-text">Profile</span>
            </a>
          </li>

		  <li class="nav-item">
			<a class="nav-link" href="{{ url_for('base_blueprint.logout') }}">
				<i class="ni ni-user-run text-red"></i>
				<span class="nav-link-text">Logout</span>
			</a>
		  </li>
		  
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Resources</span>
        </h6>
        <!-- Navigation -->
        <ul class="navbar-nav mb-md-3">
          <li class="nav-item">
            <a class="nav-link" data-toggle="modal" data-target="#modal-default">
              <i class="ni ni-spaceship"></i>
              <span class="nav-link-text">Dashboard Help</span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>